name: CI
on: 
  pull_request: 
    branches: 
      - main

env:
  TEST_TAG: hiodanado/bun-project:prerelease
  RELEASE_TAG: hiodanado/bun-project:latest

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Prerelase Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          target: prerelease
          tags: ${{ env.TEST_TAG }}
      - name: Build
        run: |
          docker run --rm $TEST_TAG bun run build
      - name: Test
        run: |
          docker run --rm $TEST_TAG bun run test
      - name: Build Release Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: release
          tags: ${{ env.RELEASE_TAG }}
